mtab=("\t\t\t")
mtab2=("\t\t")
mtab3=("\t\t\t\t")
mtab4=("\t")
mtab5=("\t\t\t\t\t")
name=input("Enter Candidate's Name : ")
cname=input("Enter Course Name: ")
ccode=input("Enter Course Code : ")
regno=input("Enter Registration No : ")
enrollno=int(input("Enter Enrollment Number : "))
date=input("enter date :")
marks1=eval(input("Enter the marks obtained in fire extinction : "))
marks2=eval(input("Enter the marks obtained in fire protection : "))
marks3=eval(input("Enter the marks obtained in fire technology : "))
marks4=eval(input("Enter the marks obtained in construction safety : "))
marks5=eval(input("Enter the marks obtained in practical 1 : "))
marks6=eval(input("Enter the marks obtained in practical 2 : "))
marks=(marks1+marks2+marks3+marks4+marks5+marks6)
percentage=((marks1+marks2+marks3+marks4+marks5+marks6)/600)*100
print("-----------------------------------------------------------------------------------------------------------------------\n")
print(mtab,"ALL INDIA INSTITUTE OF FIRE TECHNOLOGY AND SAFETY")
print("\n",mtab2,"Associated with Technical and Paramedical Education Council")
print(mtab2,"An Autonomous Institution Recognized by Goverment of India")
print("\n\n",mtab3,"ANNUAL STATEMENT OF MARKS")
print("-----------------------------------------------------------------------------------------------------------------------")
print("\n",mtab4,"Name of the Candidate",mtab3,"Course Name")
print(mtab4,name,mtab5,cname)
print("-----------------------------------------------------------------------------------------------------------------------")
print("\n",mtab4,"Course Code",mtab4,"Reg.No.",mtab4,"Enrollment No.")
print(mtab4,ccode,mtab4,regno,mtab4,enrollno)
print("-----------------------------------------------------------------------------------------------------------------------")
print("Subject Code",mtab4,"Subject Name",mtab2,"Max.Marks",mtab4,"Marks Obtained")
print("ADIFSO017",mtab4,"Fire Extension",mtab4,"100",mtab2,marks1)
print("ADIFSO018",mtab4,"Fire Protection",mtab4,"100",mtab2,marks2)
print("ADIFSO019",mtab4,"Fire Technology",mtab4,"100",mtab2,marks3)
print("ADIFSO020",mtab4,"Construction Safety",mtab4,"100",mtab2,marks4)
print("ADIFSO024",mtab4,"Practical - I",mtab2,"100",mtab2,marks5)
print("ADIFSO025",mtab4,"Practical- II",mtab2,"100",mtab2,marks6)
print("-----------------------------------------------------------------------------------------------------------------------")
print("Grand Total : ",marks)
print("-----------------------------------------------------------------------------------------------------------------------")
print("Month and Year of Examination",mtab4,"No. of Subject Offered",mtab4,"Percentage")
print("MAY 2020",mtab3,"T4+P2=6",mtab2,percentage,"%")
print("-----------------------------------------------------------------------------------------------------------------------")
if percentage>=90 and percentage<=100:
    print("Grade : A+","   ","PASS")
elif percentage>=80 and percentage<90:
    print("Grade : A","   ","PASS")
elif percentage>=70 and percentage<80:
    print("Grade : B+","   ","PASS")
elif percentage>=60 and percentage<70:
    print("Grade : B","   ","PASS")
elif percentage>=40 and percentage<60:
    print("Grade : c","   ","FAIL")
elif percentage>=0 and percentage<40:
    print("Grade : D","   ","FAIL ND NEED IMPROVEMENT")
else:
    print("NOT A VALID MARKS")
print("*********************************************************************************************************************\n")
print("DATE : ",date,mtab5,"DEPUTY CONTROLLEROF EXAMINATION")
print(mtab,"Subject marked * Indicates Exemption")
    
